Updated .gitlab-ci.yml file - ticketflow: Korrigiert   - Zu starke Einrückungen entfernt - #179

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -25,19 +25,19 @@ ticketflow:
     - echo "$TICKET_IIDS"
     - >
       echo "$TICKET_IIDS" | while IFS= read -r iid ; do
-        curl
-        --header "PRIVATE-TOKEN: $PROJECT_API_TOKEN"
-        --header "Content-Type: application/json"
-        --request PUT
-        --data "$(printf '{"add_labels":"%s"}' "$TICKET_DONE_LABEL")"
-        "$(printf "$PUT_ISSUE_URL_UNFORMATTED" "${iid}")" | jq -r '.labels[]';
+      curl
+      --header "PRIVATE-TOKEN: $PROJECT_API_TOKEN"
+      --header "Content-Type: application/json"
+      --request PUT
+      --data "$(printf '{"add_labels":"%s"}' "$TICKET_DONE_LABEL")"
+      "$(printf "$PUT_ISSUE_URL_UNFORMATTED" "${iid}")" | jq -r '.labels[]';
       done
     - 'MERGE_REQ_INTO_MAIN="$(curl -s --header "PRIVATE-TOKEN: $PROJECT_API_TOKEN" $GET_MERGE_REQ_INTO_MAIN_URL)"'
     - MERGE_REQ_INTO_MAIN_COUNT="$(echo "$MERGE_REQ_INTO_MAIN" | jq -r ". | length")"
     - >
       if [[ "$MERGE_REQ_INTO_MAIN_COUNT" != '1' ]]; then
-        echo "ERROR: There is not exactly ONE merge request pointing from ${CI_COMMIT_BRANCH} to ${CI_DEFAULT_BRANCH} (there are ${MERGE_REQ_INTO_MAIN_COUNT}: $(echo "$MERGE_REQ_INTO_MAIN" | jq -r '.[].iid'))";
-        exit 1;
+      echo "ERROR: There is not exactly ONE merge request pointing from ${CI_COMMIT_BRANCH} to ${CI_DEFAULT_BRANCH} (there are ${MERGE_REQ_INTO_MAIN_COUNT}: $(echo "$MERGE_REQ_INTO_MAIN" | jq -r '.[].iid'))";
+      exit 1;
       fi
     - UPDATED_DESCRIPTION="$(echo "$MERGE_REQ_INTO_MAIN" | jq '.[0].description' | sed -e 's/^\"//g' -e 's/\"$//g')\n\n$(echo "$MERGE_REQ" | jq '.[0].description' | sed -e 's/^\"//g' -e 's/\"$//g')"
     - >
